Added all files for Network Analysis
ubcecon/comet-open pull request #26
Opened 2024-10-31 19:53 UTC by Alexr951

I followed the format in 4_advanced/advanced_geospatial
- added all images under the media folder
- added our two .xls datsets under network_analysis_datasets
- added three .qmd notebooks which were used in our presentation.

I am unsure if this is the correct approach to not break the website, please have a look at what I did and please let me know if anything is missing or should be updated.

2025-02-01 18:07 UTC, jlgraves-ubc requested changes
Looks good, but needs some revisions.

2025-02-01 18:07 UTC, jlgraves-ubc commented on project/docs/4_Advanced/advanced_network_analysis/media/abstraction_of_NA_research_process.png
Can you double check copyright on all media files?

2025-02-01 18:07 UTC, jlgraves-ubc commented on project/docs/4_Advanced/advanced_network_analysis/network_analysis_datasets/vistorian_locations.xls
Ditto for data files.

2025-02-01 18:07 UTC, jlgraves-ubc commented on project/docs/4_Advanced/advanced_network_analysis/intro_to_python_network_analysis.qmd
@jmplatt you might find this helpful.

2025-02-01 18:07 UTC, jlgraves-ubc commented on project/docs/4_Advanced/advanced_network_analysis/intro_to_python_network_analysis.qmd
> +<div class="alert alert-block alert-warning">
Please do not use bootstrap `divs` if possible; use quarto `callout` and native ::: dives

2025-02-01 18:07 UTC, jlgraves-ubc commented on project/docs/4_Advanced/advanced_network_analysis/network_analysis_notebook.qmd
> +jupyter:
Please remove the `jupyter` block in the YAML header

2025-02-01 18:07 UTC, jlgraves-ubc commented on project/docs/4_Advanced/advanced_network_analysis/network_analysis_notebook.qmd
> + <figure>
Revise: use quarto embeds for images.

2025-02-01 18:07 UTC, jlgraves-ubc commented on project/docs/4_Advanced/advanced_network_analysis/network_analysis_notebook.qmd
> +<div style="display: flex; align-items: center;">
Ditto here; use quarto, not raw HTML.

2025-02-01 18:07 UTC, jlgraves-ubc commented on project/docs/4_Advanced/advanced_network_analysis/network_analysis_notebook.qmd
> +If you want to read the NetworkX documentation you can follow the link: https://networkx.org/documentation/stable/reference/introduction.html This link shows what kind of commands exist within the Ne
Hyperlink links

2025-02-01 18:07 UTC, jlgraves-ubc commented on project/docs/4_Advanced/advanced_network_analysis/network_analysis_notebook.qmd
> +
I think this block should be split about here, right?

2025-02-01 18:07 UTC, jlgraves-ubc commented on project/docs/4_Advanced/advanced_network_analysis/network_analysis_notebook_II.qmd
> +jupyter:
As above; remove.

2025-02-01 18:07 UTC, jlgraves-ubc commented on project/docs/4_Advanced/advanced_network_analysis/network_analysis_notebook_II.qmd
> +### 3 What is the number of edges?
Add newline before blocks

2025-02-01 18:07 UTC, jlgraves-ubc commented on project/docs/4_Advanced/advanced_network_analysis/network_analysis_notebook_II.qmd
> +## 5 Diffusion
Inconsistent punctuation.

2025-02-01 18:07 UTC, jlgraves-ubc commented on project/docs/4_Advanced/advanced_network_analysis/network_analysis_notebook_II.qmd
> +<figure>
As above re: figures.

2025-02-02 03:09 UTC, Alexr951 commented on project/docs/4_Advanced/advanced_network_analysis/media/abstraction_of_NA_research_process.png
All media files except for 'abstraction_of_NA_research_process.png' and 'networks.png' are our own screenshots, the two previous ones come from the book Introducing Network Science for Archaeology from Cambridge University Press which we cited so it should be okay.

2025-02-02 03:11 UTC, Alexr951 commented on project/docs/4_Advanced/advanced_network_analysis/network_analysis_datasets/vistorian_locations.xls
The datasets come from https://archaeologicalnetworks.wordpress.com/ 

"This tutorial teaches you how to upload network data to The Vistorian online and how to explore its different visualisation features. [The Vistorian](http://vistorian.net/) is a free-to-use online service developed by Benjamin Bach." Is written on the website so it should be okay to use the dataset and we also cited where it comes from which the authors ask to do.

2025-02-21 21:08 UTC, jlgraves-ubc approved these changes

2025-02-21 21:08 UTC, merged